#ifndef GLOBAL_VAR_H
#define	GLOBAL_VAR_H

extern aptr gl_app;
extern aptr gl_review;
extern aptr gl_charset;
extern aptr gl_protocol;
extern struct IClass *gl_class_cps;
extern struct IClass *gl_class_revarea;
extern struct IClass *gl_class_review;
extern struct IClass *gl_class_protocol;
extern struct Catalog *gl_catalog;
extern struct Locale *gl_locale;
extern aptr win_fake;
extern void (*gl_mui_id)(ulong);
extern void (*gl_mui_oc)(void);
extern void (*gl_req)(void);
extern aptr gl_pool;
extern struct Screen * gl_conscreen;
extern aptr gl_vi;
extern struct Window * gl_conwindow;
extern struct Window * gl_linwindow;
extern struct Process * gl_process;
extern struct XP_Sub * gl_proc_xp;
extern ulong gl_tmp_abort;
extern unsigned char gl_upstring[STRSIZE];
extern unsigned char gl_dnstring[STRSIZE];
extern struct FlowString gl_autoxfer[3];
extern bptr gl_asc_fh;
extern long gl_asc_mode;
extern bptr gl_cap_fh;
extern UBYTE * gl_cap_buf;
extern UBYTE * gl_cap_now;
extern LONG gl_cap_bufsize;
extern ubyte * gl_txdbuffer;
extern long    gl_txdhalt;
extern LONG gl_txdsize;
extern long gl_txdleft;
extern ULONG gl_xemsig;
extern ULONG gl_wakesig;
extern ULONG gl_rxdsig;
extern ULONG gl_txdsig;
extern struct Info * gl_onlinepb;
extern ulong gl_onlinecost;
extern ulong gl_onlinetime;
extern ulong gl_onlinebase;
extern char gl_onlinephone[STRSIZE];
extern char gl_def_all[64];
extern char gl_def_cs [64];
extern char gl_def_cu [64];
extern char gl_def_dl [64];
extern char gl_def_gl [64];
extern char gl_def_pb [64];
extern char gl_def_sl [64];
extern char gl_def_tb [64];
extern char gl_def_xm [64];
extern char gl_def_xp [64];
extern struct List gl_phonebook;
extern struct List gl_fileid;
extern struct Info * gl_defbbs;
extern struct Info * gl_fromdef;
extern struct Info * gl_curbbs;
extern unsigned char * gl_cur_qs[43];
extern ULONG gl_cur_qv[66];
extern ULONG *gl_cur_qd[2];
extern unsigned char **gl_str_ultimate;
extern ULONG *gl_val_ultimate;
extern ULONG **gl_dat_ultimate;
extern struct XEM_IO gl_xem_io;
extern struct List gl_xem_key;
extern struct Info * gl_curcs;
extern struct Info * gl_curtb;
extern struct Info * gl_curxp;
extern struct Info * gl_curxm;
extern UBYTE * gl_curtxd;
extern UBYTE * gl_currxd;
extern UBYTE * gl_curcap;
extern LONG gl_exit;
extern LONG gl_sleep;
extern LONG gl_warning;
extern LONG gl_title;
extern LONG gl_hardstat;
extern LONG gl_serok;
extern LONG gl_serfreeze;
extern LONG gl_menufreeze;
extern LONG gl_scrok;
extern LONG gl_dial;
extern LONG gl_dialnum;
extern LONG gl_xferon;
extern LONG gl_xferend;
extern long gl_async_dos;
extern LONG gl_charsafe;
extern LONG gl_macrosafe;
extern LONG gl_profsafe;
extern LONG gl_phonesafe;
extern LONG gl_protosafe;
extern long gl_showsafe;
extern LONG gl_xemsafe;
extern LONG gl_toolbarsafe;

extern long  gl_call_alloc;
extern long  gl_call_free; 
extern long  gl_call_force;
extern long  gl_tags_now;  
extern long  gl_tags_ign;  
extern long  gl_tags_add;  
extern long  gl_tags_del;  
extern long  gl_mem_now;   
extern long  gl_mem_add;  
extern long  gl_mem_del;

#endif
