/****************************************************************
  This is just for DreamTerm as it won't use builtin language
****************************************************************/

#define MSG_nil 0
#define MSG_new_entry 1
#define MSG_load 2
#define MSG_save 3
#define MSG_append 4
#define MSG_save_selected 5
#define MSG_close 6
#define MSG_note 7
#define MSG_ok 8
#define MSG_ok_cancel 9
#define MSG_project 10
#define MSG_current_settings 11
#define MSG_profile 12
#define MSG_profile_phone_prefix 13
#define MSG_character_sets 14
#define MSG_protocols 15
#define MSG_external_emulations 16
#define MSG_toolbars 17
#define MSG_load_configuration 18
#define MSG_save_configuration 19
#define MSG_titlebar 20
#define MSG_temporary_directory 21
#define MSG_initstring 22
#define MSG_priority 23
#define MSG_neg_3 24
#define MSG_0 25
#define MSG_3 26
#define MSG_crypt_settings 27
#define MSG_phonebook_crypting 28
#define MSG_auto_phonebook_save 29
#define MSG_dispose_window_objects 30
#define MSG_logfile 31
#define MSG_not_active 32
#define MSG_calls 33
#define MSG_about 34
#define MSG_quit 35
#define MSG_phonebook 36
#define MSG_directory 37
#define MSG_create_entry 38
#define MSG_load_default_phonebook 39
#define MSG_save_default_phonebook 40
#define MSG_dial_number 41
#define MSG_dial_next_selected 42
#define MSG_send_current_password 43
#define MSG_transfer 44
#define MSG_upload 45
#define MSG_upload_using_list 46
#define MSG_download 47
#define MSG_send_ascii 48
#define MSG_send_ascii_no_conv 49
#define MSG_abort_send 50
#define MSG_edit_upload_list 51
#define MSG_upload_path 52
#define MSG_download_path 53
#define MSG_protocol 54
#define MSG_auto_transfer 55
#define MSG_minimal_transfer_status 56
#define MSG_double_buffer 57
#define MSG_review_buffer 58
#define MSG_active 59
#define MSG_view 60
#define MSG_size 61
#define MSG_capture 62
#define MSG_text 63
#define MSG_raw 64
#define MSG_open_capture 65
#define MSG_close_capture 66
#define MSG_serial 67
#define MSG_dte_rate 68
#define MSG_300 69
#define MSG_1200 70
#define MSG_2400 71
#define MSG_4800 72
#define MSG_9600 73
#define MSG_14400 74
#define MSG_19200 75
#define MSG_38400 76
#define MSG_57600 77
#define MSG_76800 78
#define MSG_115200 79
#define MSG_enter 80
#define MSG_databits 81
#define MSG_7 82
#define MSG_8 83
#define MSG_parity 84
#define MSG_none 85
#define MSG_even 86
#define MSG_odd 87
#define MSG_mark 88
#define MSG_space 89
#define MSG_stopbits 90
#define MSG_1 91
#define MSG_2 92
#define MSG_flow_control 93
#define MSG_xon_xoff 94
#define MSG_rts_cts 95
#define MSG_duplex 96
#define MSG_half 97
#define MSG_full 98
#define MSG_serial_device 99
#define MSG_serial_unit 100
#define MSG_serial_shared 101
#define MSG_fixed_dte_rate 102
#define MSG_hardware_serial 103
#define MSG_drop_dtr_to_hangup 104
#define MSG_serial_active 105
#define MSG_hangup 106
#define MSG_screen 107
#define MSG_screen_mode 108
#define MSG_columns 109
#define MSG_lines 110
#define MSG_status 111
#define MSG_nothing 112
#define MSG_line 113
#define MSG_window 114
#define MSG_status_line 115
#define MSG_charset 116
#define MSG_show_hardware_screen 117
#define MSG_borderblank 118
#define MSG_keep_workbench_colors 119
#define MSG_enable_aga_bandwith 120
#define MSG_hardware_screen 121
#define MSG_auto_rxd_popup 122
#define MSG_rts_blit 123
#define MSG_force_screenreqs_size 124
#define MSG_use_public_screen 125
#define MSG_public_screen_name 126
#define MSG_txd_crlf_conversion 127
#define MSG_cr_to_crlf 128
#define MSG_lf_to_crlf 129
#define MSG_layout 130
#define MSG_vertical 131
#define MSG_horizontal 132
#define MSG_toolbar 133
#define MSG_emulation 134
#define MSG_ansi_vt102 135
#define MSG_hex 136
#define MSG_xem 137
#define MSG_reset 138
#define MSG_ansi_setup 139
#define MSG_prescroll 140
#define MSG_line_wrap 141
#define MSG_destructive_backspace 142
#define MSG_strip_bold 143
#define MSG_esc2j_homes_cursor 144
#define MSG_cr_lf_to_cr_lf 145
#define MSG_pc_ansi 146
#define MSG_xem_setup 147
#define MSG_change_options 148
#define MSG_special 149
#define MSG_direct_print 150
#define MSG_run_command 151
#define MSG_current_phonebook_is_not_saved 152
#define MSG_name 153
#define MSG_comment 154
#define MSG_dial_prefix 155
#define MSG_password 156
#define MSG_download_list 157
#define MSG_hangup_string 158
#define MSG_dial_suffix 159
#define MSG_no_carrier 160
#define MSG_no_dialtone 161
#define MSG_connect 162
#define MSG_ringing 163
#define MSG_error 164
#define MSG_busy 165
#define MSG_ok_string 166
#define MSG_dial_abort 167
#define MSG_call_cost 168
#define MSG_minute_cost 169
#define MSG_serial_buffer 170
#define MSG_hardware_lines 171
#define MSG_wait_between_dials 172
#define MSG_wait_dialing 173
#define MSG_f1 174
#define MSG_f2 175
#define MSG_f3 176
#define MSG_f4 177
#define MSG_f5 178
#define MSG_f6 179
#define MSG_f7 180
#define MSG_f8 181
#define MSG_f9 182
#define MSG_f10 183
#define MSG_log_calls 184
#define MSG_review 185
#define MSG_review_lines 186
#define MSG_options 187
#define MSG_key_add 188
#define MSG_key_delete 189
#define MSG_key_ok 190
#define MSG_key_cancel 191
#define MSG_mui_ok_cancel 192
#define MSG_closing_screen_you_must_close_all_windows 193
#define MSG_dreamterm_scr_title 194
#define MSG_cannot_open_requested_screen_trying_workbench 195
#define MSG_cannot_find_public_screen_trying_workbench 196
#define MSG_cannot_find_public_screen 197
#define MSG_dreamterm_win_title 198
#define MSG_cannot_open_console 199
#define MSG_cannot_init_console 200
#define MSG_cannot_modify_console 201
#define MSG_cannot_init_serial 202
#define MSG_out_of_memory 203
#define MSG_cannot_wake_up 204
#define MSG_cannot_save_current_settings 205
#define MSG_cannot_read_profile 206
#define MSG_cannot_save_profile 207
#define MSG_cannot_save_default_profile 208
#define MSG_unable_to_continue 209
#define MSG_cannot_load_use_current_settings 210
#define MSG_cannot_open_font_for_hardware_screen 211
#define MSG_charset_configuration 212
#define MSG_select_font 213
#define MSG_cannot_open_font 214
#define MSG_load_txd_conversion_table 215
#define MSG_loaded_conversion_table_incomplete_current_not_changed 216
#define MSG_cannot_open_conversion_table 217
#define MSG_load_rxd_conversion_table 218
#define MSG_load_capture_conversion_table 219
#define MSG_width 220
#define MSG_heigth 221
#define MSG_current_configuration_is_not_saved 222
#define MSG_this_will_change_your_life 223
#define MSG_program_modules_show_no_more 224
#define MSG_about1 225
#define MSG_who_needs_this_information 226
#define MSG_about2 227
#define MSG_online 228
#define MSG_phonebook_directory 229
#define MSG_toolbar_configuration 230
#define MSG_protocol_configuration 231
#define MSG_xemulation_configuration 232
#define MSG_character_set_configuration 233
#define MSG_are_you_sure_to_quit 234
#define MSG_enter_numbers_to_dial 235
#define MSG_select_file 236
#define MSG_select_file_no_conversion 237
#define MSG_overwrite_append_cancel 238
#define MSG_file_x_already_exist 239
#define MSG_crypting_options 240
#define MSG_library 241
#define MSG_dialing_manually 242
#define MSG_dialing 243
#define MSG_phone 244
#define MSG_modem 245
#define MSG_add_time 246
#define MSG_skip 247
#define MSG_abort 248
#define MSG_force_connect 249
#define MSG_x_seconds_left_for_succesful_connection 250
#define MSG_x_seconds_left_for_waiting 251
#define MSG_x_tries_x_seconds_used 252
#define MSG_no_name 253
#define MSG_enter_new_number 254
#define MSG_droplist 255
#define MSG_x_x_mb_time 256
#define MSG_select_files_to_add 257
#define MSG_combined_size 258
#define MSG_estimated_cps 259
#define MSG_upload_list 260
#define MSG_delete_all 261
#define MSG_fi_upload 262
#define MSG_warning 263
#define MSG_change_profile_phone_prefix 264
#define MSG_raw_direct_to_emulation 265
#define MSG_enter_command_arguments 266
#define MSG_select_tempdir 267
#define MSG_startup_initstring 268
#define MSG_select_upload_path 269
#define MSG_select_download_path 270
#define MSG_pb_edit_droplist 271
#define MSG_pb_edit_showlist 272
#define MSG_pb_ascending 273
#define MSG_pb_descending 274
#define MSG_pb_selected 275
#define MSG_pb_load_new_phonebook 276
#define MSG_pb_append_new_phonebook 277
#define MSG_pb_save_phonebook 278
#define MSG_pb_how_many_hours_to_freeze 279
#define MSG_pb_select_showlist 280
#define MSG_pb_cannot_load_complete_phonebook 281
#define MSG_pb_cannot_decrypt_phonebook 282
#define MSG_pb_showlist 283
#define MSG_pb_dial 284
#define MSG_pb_unselect 285
#define MSG_pb_add 286
#define MSG_pb_clone 287
#define MSG_pb_edit 288
#define MSG_pb_delete 289
#define MSG_pb_drop_away 290
#define MSG_pb_freeze 291
#define MSG_pb_reset 292
#define MSG_pb_enter_password 293
#define MSG_pb_cannot_crypt_phonebook 294
#define MSG_pb_cannot_save_phonebook 295
#define MSG_bbs 296
#define MSG_keyboard 297
#define MSG_line_window 298
#define MSG_external_xem 299
#define MSG_black_background 300
#define MSG_red 301
#define MSG_green 302
#define MSG_yellow 303
#define MSG_blue 304
#define MSG_magenta 305
#define MSG_cyan 306
#define MSG_white 307
#define MSG_black_bright 308
#define MSG_red_bright 309
#define MSG_green_bright 310
#define MSG_yellow_bright 311
#define MSG_blue_bright 312
#define MSG_magenta_bright 313
#define MSG_cyan_bright 314
#define MSG_white_bright 315
#define MSG_background 316
#define MSG_screen_dimension_x_x_pixels_x_colors 317
#define MSG_disable_option_to_pick_it_from_profile 318
#define MSG_disable_option_to_make_it_default_pick_from_profile 319
#define MSG_disable_option_to_pick_it_from_local_here 320
#define MSG_disable_option_to_make_it_default_pick_from_local_here 321
#define MSG_yes_discard 322
#define MSG_phonenumber_is_in_droplist 323
#define MSG_pe_public_screen_name 324
#define MSG_pe_force_screenreqs_size 325
#define MSG_pe_hardware_lines 326
#define MSG_default 327
#define MSG_brighter 328
#define MSG_copy_8 329
#define MSG_pe_prescroll 330
#define MSG_pe_set_pick 331
#define MSG_pe_clear_pick 332
#define MSG_pe_editing_phonebook_entry 333
#define MSG_no_memory_to_edit_entry 334
#define MSG_creating_new_phonebook_entry 335
#define MSG_cannot_create_entry 336
#define MSG_editing_profile 337
#define MSG_editing_current_settings 338
#define MSG_pe_use_public_screen 339
#define MSG_pe_status_line 340
#define MSG_xp_protocol_configuration 341
#define MSG_xp_select_xpr_protocol_library 342
#define MSG_xp_xpr_library 343
#define MSG_xp_init_string 344
#define MSG_xp_auto_upload 345
#define MSG_xp_auto_download 346
#define MSG_xp_xpr 347
#define MSG_xp_external 348
#define MSG_xp_upload_dos 349
#define MSG_xp_download_dos 350
#define MSG_alloc_force_error 351
#define MSG_phone_prefix 352
#define MSG_crypting_library 353
#define MSG_packing_library 354
#define MSG_crypting_phrase 355
#define MSG_obsolete 356
#define MSG_depth 357
#define MSG_last_called 358
#define MSG_total_cost 359
#define MSG_total_time 360
#define MSG_total_calls 361
#define MSG_sent_bytes 362
#define MSG_received_bytes 363
#define MSG_console_x 364
#define MSG_console_y 365
#define MSG_overscan 366
#define MSG_autoscroll 367
#define MSG_freeze 368
#define MSG_toolbar_active 369
#define MSG_toolbar_layout 370
#define MSG_no_command 371
#define MSG_edit_current_settings 372
#define MSG_edit_profile 373
#define MSG_edit_protocols 374
#define MSG_edit_character_sets 375
#define MSG_edit_emulations 376
#define MSG_edit_toolbar 377
#define MSG_edit_crypt_settings 378
#define MSG_edit_phonebook 379
#define MSG_view_review 380
#define MSG_release_serial 381
#define MSG_xx_mb 382
#define MSG_on 383
#define MSG_off 384
#define MSG_load_profile 385
#define MSG_save_profile 386
#define MSG_showlist_configuration 387
#define MSG_select_tag 388
#define MSG_control 389
#define MSG_move_up 390
#define MSG_move_down 391
#define MSG_add_tag 392
#define MSG_delete_tag 393
#define MSG_tb_toolbar_configuration 394
#define MSG_internal_empty 395
#define MSG_mui_is_remapping_image 396
#define MSG_loading_image 397
#define MSG_select_picture 398
#define MSG_format 399
#define MSG_dos 400
#define MSG_action 401
#define MSG_tb_add 402
#define MSG_tb_delete 403
#define MSG_xem_configuration 404
#define MSG_select_xem_library 405
#define MSG_xem_library 406
#define MSG_settings 407
#define MSG_colors_to_use 408
#define MSG_xm_change_options 409
#define MSG_xm_reset 410
#define MSG_xw_name 411
#define MSG_xw_size 412
#define MSG_xw_time 413
#define MSG_xw_cps 414
#define MSG_xw_bytes 415
#define MSG_xw_blocksize 416
#define MSG_xw_block_crc 417
#define MSG_xw_msg 418
#define MSG_xw_error 419
#define MSG_xw_skip 420
#define MSG_xw_abort 421
#define MSG_select_files_to_upload 422
#define MSG_cannot_open_xpr_library 423
#define MSG_enter_receive_filename 424
