; --> Emulaation flaggeja (ChangeANSI)

ANSI_INIT	EQU 0	; BITDEFS (NOT LIKE ANSIEXT!!!)
ANSI_WRAP	EQU 1
ANSI_KILLBS	EQU 2
ANSI_CRLF	EQU 3
ANSI_STRIPBOLD	EQU 4
ANSI_CLRHOME	EQU 6
ANSI_16COL	EQU 5
ANSI_8COL	EQU 7
ANSI_4COL	EQU 8
ANSI_2COL	EQU 9
